name: Release

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write # Required for provenance and trusted publishing
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check & Build
        run: bun run check && bun run build

      - name: Create Release Pull Request or Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run changeset publish --provenance
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
